Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "sakila-db.dev"
  config.vm.network "private_network", ip: "192.168.80.80"
  config.vm.synced_folder "../", "/var/www/sakila-db.dev", owner: "www-data", group: "www-data"
  config.vm.provision "shell", path: "LASP.sh"
  config.vm.provision "shell", inline: "service apache2 restart", run: "always"

end